#!/usr/bin/env python3
"""
External reference for the 3-elevator, 4-floor simulation.

Reads `out/elevator-framework.json` (which contains the deterministic
arrival schedule generated by the TypeScript framework's mulberry32) and
runs the SAME dispatch logic in SimPy on continuous time (no fixed time-
step). Then writes `out/external/elevator/simpy.json` with per-person
records and aggregate metrics.

The TypeScript framework discretizes time at dt=0.5 s and applies SCAN/LOOK
once per tick; SimPy applies SCAN/LOOK at exactly the moment events fire.
Aggregate metrics (mean wait, mean travel, mean total) should agree to
within roughly half the framework's stepSize.

Usage (called by external-references/run-all.sh):
    python3 elevator.py
"""
import json
import os
import pathlib
import statistics
import sys
from collections import deque
from dataclasses import dataclass, field
from typing import List, Optional

import simpy

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent.parent
IN_PATH = ROOT / "out" / "elevator-framework.json"
OUT_DIR = ROOT / "out" / "external" / "elevator"
OUT_PATH = OUT_DIR / "simpy.json"


@dataclass
class Person:
    pid: int
    from_floor: int
    to_floor: int
    arrival: float
    board:   float = -1.0
    exit:    float = -1.0
    @property
    def direction(self) -> str:
        return "up" if self.to_floor > self.from_floor else "down"


@dataclass
class Floor:
    n: int
    up_q:   deque = field(default_factory=deque)
    down_q: deque = field(default_factory=deque)
    def add(self, p: Person) -> None:
        (self.up_q if p.direction == "up" else self.down_q).append(p)
    def has_call(self, direction: str) -> bool:
        q = self.up_q if direction == "up" else self.down_q
        return len(q) > 0
    def take(self, direction: str, cap: int) -> List[Person]:
        q = self.up_q if direction == "up" else self.down_q
        out = []
        while q and len(out) < cap:
            out.append(q.popleft())
        return out


class Building:
    def __init__(self, env: simpy.Environment, n_floors: int, n_elevators: int,
                 capacity: int, travel_t: float, service_t: float):
        self.env = env
        self.floors = [Floor(i + 1) for i in range(n_floors)]
        self.elevators: List["Elevator"] = []
        for k in range(n_elevators):
            self.elevators.append(Elevator(
                env, k, self.floors, capacity, travel_t, service_t,
                start_floor=1 + (k % n_floors),
            ))
        # Wake-up event: triggered whenever a new call appears or an elevator
        # finishes serving and might pick a different target. We re-create
        # the event each time it fires (one-shot semantics).
        self._wake = env.event()

    def trigger(self) -> None:
        if not self._wake.triggered:
            self._wake.succeed()
        self._wake = self.env.event()

    def wake(self) -> simpy.Event:
        return self._wake


class Elevator:
    def __init__(self, env: simpy.Environment, idx: int, floors: List[Floor],
                 capacity: int, travel_t: float, service_t: float, start_floor: int):
        self.env = env
        self.idx = idx
        self.floors = floors
        self.capacity = capacity
        self.travel_t = travel_t
        self.service_t = service_t
        self.current_floor: float = float(start_floor)
        self.passengers: List[Person] = []
        self.direction: str = "idle"
        self.building: Optional[Building] = None

    def attach(self, b: Building) -> None:
        self.building = b
        self.env.process(self.run())

    def run(self):
        while True:
            target = self._pick_next_target()
            if target is None:
                self.direction = "idle"
                yield self.building.wake()
                continue
            floor, direction = target
            self.direction = direction
            travel = abs(floor - self.current_floor) * self.travel_t
            yield self.env.timeout(travel)
            self.current_floor = float(floor)
            # SERVING
            f = self.floors[int(self.current_floor) - 1]
            now = self.env.now
            # deboard
            stay, leave = [], []
            for p in self.passengers:
                if p.to_floor == int(self.current_floor):
                    p.exit = now
                    leave.append(p)
                else:
                    stay.append(p)
            self.passengers = stay
            # board
            slots = self.capacity - len(self.passengers)
            for p in f.take(direction, slots):
                p.board = now
                self.passengers.append(p)
            yield self.env.timeout(self.service_t)
            # New target may now exist; trigger so other idle elevators wake too.
            self.building.trigger()

    def _pick_next_target(self):
        cur = self.current_floor

        def try_dir(direction):
            best = None
            for p in self.passengers:
                if (direction == "up" and p.to_floor > cur) or \
                   (direction == "down" and p.to_floor < cur):
                    if best is None or (
                        (direction == "up" and p.to_floor < best) or
                        (direction == "down" and p.to_floor > best)):
                        best = p.to_floor
            for f in self.floors:
                if (direction == "up" and f.n > cur) or \
                   (direction == "down" and f.n < cur):
                    if f.has_call(direction):
                        if best is None or (
                            (direction == "up" and f.n < best) or
                            (direction == "down" and f.n > best)):
                            best = f.n
            return (best, direction) if best is not None else None

        if self.direction == "up":
            t = try_dir("up")
            if t: return t
            t = try_dir("down")
            if t: return t
        elif self.direction == "down":
            t = try_dir("down")
            if t: return t
            t = try_dir("up")
            if t: return t
        # idle: nearest call anywhere
        best_d = float("inf"); best_floor = None; best_dir = "up"
        for f in self.floors:
            d = abs(f.n - cur)
            if f.has_call("up") and d < best_d:
                best_d = d; best_floor = f.n; best_dir = "up"
            if f.has_call("down") and d < best_d:
                best_d = d; best_floor = f.n; best_dir = "down"
        return (best_floor, best_dir) if best_floor is not None else None


def arrivals_process(env: simpy.Environment, building: Building,
                     schedule: List[dict], persons: List[Person]):
    for entry in schedule:
        # Wait until that arrival time, then enqueue.
        delay = entry["t"] - env.now
        if delay > 0:
            yield env.timeout(delay)
        p = Person(pid=len(persons), from_floor=entry["fromFloor"],
                   to_floor=entry["toFloor"], arrival=entry["t"])
        persons.append(p)
        building.floors[p.from_floor - 1].add(p)
        building.trigger()


def main() -> int:
    if not IN_PATH.exists():
        print(f"[elevator] input {IN_PATH} not found; "
              f"run `node dist/des/main-elevator.js` first.", file=sys.stderr)
        return 1
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    with IN_PATH.open() as f:
        payload = json.load(f)

    cfg = payload["config"]
    schedule = payload["schedule"]

    env = simpy.Environment()
    b = Building(env, cfg["nFloors"], cfg["nElevators"], cfg["capacity"],
                 cfg["floorTravelTime"], cfg["serviceTime"])
    for el in b.elevators:
        el.attach(b)
    persons: List[Person] = []
    env.process(arrivals_process(env, b, schedule, persons))

    # Run long enough to drain everyone (allow extra time after last arrival).
    env.run(until=cfg["simT"] + 1000)

    served = [p for p in persons if p.exit > 0]
    waits = [p.board - p.arrival for p in served]
    travels = [p.exit - p.board for p in served]
    totals = [p.exit - p.arrival for p in served]

    def p95(xs):
        if not xs: return 0.0
        s = sorted(xs)
        return s[int(0.95 * (len(s) - 1))]

    aggregates = {
        "n": len(persons),
        "nServed": len(served),
        "meanWait":   statistics.fmean(waits) if waits else 0.0,
        "meanTravel": statistics.fmean(travels) if travels else 0.0,
        "meanTotal":  statistics.fmean(totals) if totals else 0.0,
        "p95Wait":  p95(waits),
        "p95Total": p95(totals),
    }

    out = {
        "tool": "simpy (continuous-time event-driven)",
        "config": cfg,
        "people": [
            {"id": p.pid, "fromFloor": p.from_floor, "toFloor": p.to_floor,
             "arrivalTime": p.arrival, "boardTime": p.board, "exitTime": p.exit}
            for p in served
        ],
        "aggregates": aggregates,
    }
    with OUT_PATH.open("w") as f:
        json.dump(out, f)
    print(f"[elevator] served {aggregates['nServed']}/{aggregates['n']} people")
    print(f"[elevator] meanWait={aggregates['meanWait']:.2f}s "
          f"meanTravel={aggregates['meanTravel']:.2f}s "
          f"meanTotal={aggregates['meanTotal']:.2f}s")
    print(f"[elevator] wrote {OUT_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
