#!/usr/bin/env ts-node
'use strict';

// =============================================================================
// RUST MIGRATION  —  target: src/bin/validate-smart-traffic-external.rs  (a `fn
//                    main` binary; an `examples/…rs` also works)
// 1:1 file move. Cross-checks the smart-traffic DES against an optional external
// SUMO simulator via the sanctioned external-module registry.
//
// Conversion notes (file-specific):
//   - CLI entry point: top-level code becomes `fn main()`.
//   - `fs`/`path` + `child_process` (SUMO/netconvert) -> `std::fs` /
//     `std::process::Command`.
//   - `JSON.parse`/`stringify` of demand rows + payloads -> serde structs
//     (TrafficDemandRow, CheckRow); no `as any`.
//   - `process.exit(code)` -> `std::process::exit(code)`.
// =============================================================================

// =============================================================================
// validate-smart-traffic-external.ts
//
// Cross-checks the smart traffic DES against an optional SUMO black-box
// simulator. SUMO/netconvert are never vendored; the invocation goes through the
// sanctioned external module registry and the source-only Python adapter under
// external-references/traffic/.
// =============================================================================

import './external-modules';
import * as fs from 'fs';
import * as path from 'path';
import {TRAFFIC_SUMO_REFERENCE_ID} from './external-modules';
import {repoRootFromRunner, runExternalModule} from './external-program';
import {TrafficLane, TrafficNetwork, TrafficSource} from '../general/network-flow';
import {runSmartTrafficFlow, SmartTrafficParams, SmartTrafficResult} from '../general/smart-traffic-flow';

interface CheckRow {name: string; passed: boolean; detail?: string}

interface TrafficDemandRow {
  id: string;
  sourceId: string;
  sinkId: string;
  route: string[];
  vehicles: number;
  beginSec: number;
  endSec: number;
}

interface ExternalTrafficPayload {
  status: string;
  message?: string;
  result?: {
    generatedDemand: number;
    departed: number;
    arrived: number;
    activeAtEnd: number;
    meanTravelTimeSec: number;
    meanSpeedMps: number;
    meanWaitingTimeSec: number;
    collisionCount: number;
  };
}

const ROOT = repoRootFromRunner();
const OUT_DIR = path.join(ROOT, 'out', 'external', 'traffic');
const checks: CheckRow[] = [];

function check(name: string, passed: boolean, detail?: string): void {
  checks.push({name, passed, detail});
  console.log(`  ${passed ? 'PASS' : 'FAIL'}  ${name}${detail ? ' - ' + detail : ''}`);
}

function relativeClose(name: string, actual: number, expected: number, tolerance: number): void {
  const diff = Math.abs(actual - expected);
  const rel = diff / Math.max(1, Math.abs(actual), Math.abs(expected));
  check(name, rel <= tolerance, `actual=${actual.toFixed(4)} expected=${expected.toFixed(4)} rel=${rel.toFixed(3)} tol=${tolerance}`);
}

function main(): void {
  console.log('Smart traffic DES: optional SUMO external simulator cross-check');
  console.log('================================================================');

  const params: SmartTrafficParams = {
    builtin: 'five-intersection',
    durationSec: 180,
    dtSec: 0.1,
    seed: 19,
    actorShuffleSeed: 2026,
    maxCars: 250,
    smartCarPoolSize: 400,
    spawnRateMultiplier: 1,
    carLengthM: 4.8,
    carWidthM: 1.8,
    laneWidthM: 3.7,
    minGapM: 2.5,
    maxAccelMps2: 2.2,
    maxDecelMps2: 4,
    maxJerkMps3: 6,
    reactionTimeSec: 0.8,
    timeHeadwaySec: 1.1,
    gridCellSizeM: 0.3048,
    accidentRiskScale: 0,
    accidentProbability: 0,
    distancePreferenceSpread: 0,
    startPreferenceSpread: 0,
  };

  const internal = runSmartTrafficFlow(params);
  check('internal smart traffic validators pass', internal.validation.every(c => c.passed));
  check('external cross-check uses no-accident baseline', (internal.params.accidentRiskScale ?? internal.params.accidentProbability ?? 0) === 0 && internal.crashed === 0, `crashed=${internal.crashed}`);
  check('internal baseline has observable throughput', internal.entered > 0 && internal.exited > 0, `entered=${internal.entered} exited=${internal.exited}`);

  fs.mkdirSync(OUT_DIR, {recursive: true});
  const problemPath = path.join(OUT_DIR, 'smart-traffic-sumo-problem.json');
  const outPath = path.join(OUT_DIR, 'smart-traffic-sumo-reference.json');
  const problem = {
    schema: 'des/external-traffic-sumo/v1',
    model: 'smart-traffic-flow',
    note: 'Generated by validate-smart-traffic-external.ts. Accident risk is zero because SUMO is used as a baseline car-following cross-check, not as the stochastic crash oracle.',
    params: internal.params,
    network: internal.network,
    internalSummary: compactInternalSummary(internal),
    demand: buildDemand(internal.network, internal.params, internal.entered),
  };
  fs.writeFileSync(problemPath, JSON.stringify(problem, null, 2));
  check('writes normalized external traffic problem', fs.existsSync(problemPath), problemPath);

  const ext = runExternalModule(TRAFFIC_SUMO_REFERENCE_ID, {
    problem: problemPath,
    out: outPath,
    collisionAction: 'warn',
  });
  check('external SUMO adapter process exits cleanly', ext.status === 0, `status=${ext.status}`);
  if (ext.stdout.trim()) console.log(`  external stdout: ${ext.stdout.trim()}`);
  if (ext.stderr.trim()) console.error(ext.stderr.trim());
  check('external SUMO adapter writes JSON payload', fs.existsSync(outPath), outPath);
  const payload = JSON.parse(fs.readFileSync(outPath, 'utf8')) as ExternalTrafficPayload;
  check('external payload has known status', ['ok', 'unavailable', 'error'].includes(payload.status), `status=${payload.status}`);

  if (payload.status === 'unavailable') {
    check('SUMO dependency is optional and reported cleanly', true, payload.message);
  } else if (payload.status === 'ok' && payload.result) {
    compareSUMO(internal, payload.result);
  } else {
    check('SUMO run completed without adapter error', false, payload.message ?? 'unknown external adapter error');
  }

  console.log('');
  const passed = checks.filter(c => c.passed).length;
  console.log(`validate-smart-traffic-external: ${passed}/${checks.length} checks passed.`);
  if (passed < checks.length) {
    console.log('FAILED:');
    for (const c of checks) if (!c.passed) console.log(`  - ${c.name}${c.detail ? ': ' + c.detail : ''}`);
    process.exit(1);
  }
}

function compareSUMO(internal: SmartTrafficResult, external: NonNullable<ExternalTrafficPayload['result']>): void {
  check('SUMO generated at least one vehicle', external.generatedDemand > 0, `generated=${external.generatedDemand}`);
  relativeClose('SUMO departures align with DES entered count', external.departed, internal.entered, 0.15);
  const internalExitRate = internal.entered > 0 ? internal.exited / internal.entered : 0;
  const externalExitRate = external.departed > 0 ? external.arrived / external.departed : 0;
  check('SUMO and DES completion rates are in the same broad band',
    Math.abs(internalExitRate - externalExitRate) <= 0.4,
    `internal=${internalExitRate.toFixed(3)} external=${externalExitRate.toFixed(3)}`);
  check('SUMO mean travel time is finite', Number.isFinite(external.meanTravelTimeSec) && external.meanTravelTimeSec >= 0, `mean=${external.meanTravelTimeSec}`);
  if (internal.meanTravelTimeSec > 0 && external.meanTravelTimeSec > 0) {
    const ratio = internal.meanTravelTimeSec / external.meanTravelTimeSec;
    check('SUMO and DES mean travel times are comparable order-of-magnitude',
      ratio >= 0.2 && ratio <= 5,
      `internal=${internal.meanTravelTimeSec.toFixed(3)} external=${external.meanTravelTimeSec.toFixed(3)} ratio=${ratio.toFixed(3)}`);
  }
  check('SUMO collision count is reported', external.collisionCount >= 0, `collisions=${external.collisionCount}`);
}

function compactInternalSummary(r: SmartTrafficResult): Record<string, unknown> {
  return {
    entered: r.entered,
    exited: r.exited,
    crashed: r.crashed,
    activeAtEnd: r.finalCars.length,
    dropped: r.dropped,
    meanTravelTimeSec: r.meanTravelTimeSec,
    meanSpeedMps: r.meanSpeedMps,
    maxActiveCars: r.maxActiveCars,
  };
}

function buildDemand(network: TrafficNetwork, params: SmartTrafficParams, totalVehicles: number): TrafficDemandRow[] {
  const rows: Array<TrafficDemandRow & {weight: number; fractional: number}> = [];
  const sinkById = new Map(network.sinks.map(s => [s.id, s]));
  for (const source of network.sources) {
    const sinkIds = source.destinationSinkIds ?? network.sinks.map(s => s.id);
    for (const sinkId of sinkIds) {
      const sink = sinkById.get(sinkId);
      if (!sink) continue;
      const route = shortestLanePath(network, source.nodeId, sink.nodeId);
      if (route.length === 0) continue;
      rows.push({
        id: `${source.id}-${sinkId}`,
        sourceId: source.id,
        sinkId,
        route,
        vehicles: 0,
        beginSec: 0,
        endSec: params.durationSec,
        weight: demandWeight(source, sinkIds.length),
        fractional: 0,
      });
    }
  }
  const totalWeight = rows.reduce((sum, row) => sum + row.weight, 0);
  if (totalWeight <= 0 || rows.length === 0) return [];
  let assigned = 0;
  for (const row of rows) {
    const raw = totalVehicles * row.weight / totalWeight;
    row.vehicles = Math.floor(raw);
    row.fractional = raw - row.vehicles;
    assigned += row.vehicles;
  }
  rows.sort((a, b) => b.fractional - a.fractional || a.id.localeCompare(b.id));
  for (let i = 0; assigned < totalVehicles; i++, assigned++) rows[i % rows.length].vehicles++;
  rows.sort((a, b) => a.id.localeCompare(b.id));
  return rows.map(({weight: _weight, fractional: _fractional, ...row}) => row);
}

function demandWeight(source: TrafficSource, sinkCount: number): number {
  return source.ratePerMin / Math.max(1, sinkCount);
}

function shortestLanePath(network: TrafficNetwork, startNode: string, endNode: string): string[] {
  const outgoing = new Map<string, TrafficLane[]>();
  for (const lane of network.lanes) {
    const arr = outgoing.get(lane.from) ?? [];
    arr.push(lane);
    outgoing.set(lane.from, arr);
  }
  const nodes = new Set(network.nodes.map(n => n.id));
  const dist = new Map<string, number>();
  const prevNode = new Map<string, string>();
  const prevLane = new Map<string, string>();
  for (const node of nodes) dist.set(node, Infinity);
  dist.set(startNode, 0);
  const pending = new Set(nodes);
  while (pending.size > 0) {
    let current: string | undefined;
    let best = Infinity;
    for (const node of pending) {
      const d = dist.get(node) ?? Infinity;
      if (d < best) { best = d; current = node; }
    }
    if (current === undefined || !Number.isFinite(best)) break;
    pending.delete(current);
    if (current === endNode) break;
    for (const lane of outgoing.get(current) ?? []) {
      const nd = best + lane.lengthM;
      if (nd < (dist.get(lane.to) ?? Infinity)) {
        dist.set(lane.to, nd);
        prevNode.set(lane.to, current);
        prevLane.set(lane.to, lane.id);
      }
    }
  }
  if (!prevLane.has(endNode)) return [];
  const route: string[] = [];
  let cur = endNode;
  while (cur !== startNode) {
    const laneId = prevLane.get(cur);
    const parent = prevNode.get(cur);
    if (!laneId || !parent) return [];
    route.push(laneId);
    cur = parent;
  }
  return route.reverse();
}

main();
